# Generated by Django 6.0.1 on 2026-05-31 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('lender', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(choices=[('personal_loan', 'Personal Loan'), ('credit_card', 'Credit Card'), ('mobile_loan', 'Mobile Loan'), ('mortgage', 'Mortgage'), ('sacco', 'SACCO Loan'), ('business_loan', 'Business Loan'), ('family_friend', 'Family / Friend'), ('other', 'Other')], default='personal_loan', max_length=50)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=4, default=0, help_text='Annual interest rate as a percentage e.g. 14.5 for 14.5%', max_digits=8)),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'debts',
                'ordering': ['-current_balance'],
                'indexes': [models.Index(fields=['user'], name='debts_user_id_2e82e8_idx'), models.Index(fields=['user', 'type'], name='debts_user_id_568d2c_idx')],
            },
        ),
    ]
