# Generated by Django 6.0.1 on 2026-04-19 20:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'core_user',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('phone_country_code', models.CharField(blank=True, default='', max_length=5)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country_code', models.CharField(default='KE', max_length=3)),
                ('currency_code', models.CharField(default='KES', max_length=3)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('employment_type', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('both', 'Both')], default='employed', max_length=20)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('business', 'Business')], default='free', max_length=20)),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_id', models.CharField(blank=True, default='', max_length=200)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('two_fa_method', models.CharField(choices=[('none', 'None'), ('totp', 'Authenticator App'), ('sms', 'SMS'), ('email', 'Email OTP')], default='none', max_length=10)),
                ('totp_secret', models.CharField(blank=True, default='', max_length=64)),
                ('ai_queries_this_month', models.IntegerField(default=0)),
                ('ai_queries_reset_at', models.DateTimeField(blank=True, null=True)),
                ('ai_permissions', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_profile',
            },
        ),
    ]
