# Generated by Django 6.0.1 on 2026-04-19 20:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'savings_goals',
            },
        ),
    ]
