# Generated by Django 6.0.1 on 2026-05-31 11:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('emergency', 'Emergency Fund'), ('travel', 'Travel'), ('education', 'Education'), ('business', 'Business'), ('asset', 'Asset Purchase'), ('retirement', 'Retirement'), ('other', 'Other')], default='other', max_length=50)),
                ('is_complete', models.BooleanField(default=False)),
                ('ai_coaching_message', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'savings_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('note', models.TextField(blank=True, default='')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='savings.savingsgoal')),
            ],
            options={
                'db_table': 'goal_contributions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='savingsgoal',
            index=models.Index(fields=['user'], name='savings_goa_user_id_e7b025_idx'),
        ),
        migrations.AddIndex(
            model_name='savingsgoal',
            index=models.Index(fields=['user', 'is_complete'], name='savings_goa_user_id_e54eef_idx'),
        ),
    ]
