# Generated by Django 6.0.1 on 2026-04-19 20:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('bank', 'Bank'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash'), ('investment', 'Investment'), ('credit_card', 'Credit Card'), ('crypto', 'Crypto')], max_length=50)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('institution_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
