# Generated by Django 6.0.1 on 2026-05-31 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField()),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('parameters', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('ai_narrative', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True)),
                ('status', models.CharField(default='generating', max_length=20)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
