# Generated by Django 6.0.1 on 2026-04-19 20:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField(unique=True)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('employment_type', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self Employed'), ('both', 'Both')], default='employed', max_length=20)),
                ('tax_year', models.CharField(blank=True, max_length=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('side_hustle_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'db_table': 'tax_settings',
            },
        ),
    ]
