# Generated by Django 6.0.1 on 2026-05-31 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField()),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('warning', 'Warning')], max_length=20)),
                ('fraud_type', models.CharField(blank=True, max_length=255)),
                ('ai_analysis', models.TextField(blank=True)),
                ('action_steps', models.TextField(blank=True)),
                ('legal_info', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'fraud_alerts',
            },
        ),
        migrations.CreateModel(
            name='FraudDetectionSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField(unique=True)),
                ('velocity_threshold', models.IntegerField(default=5)),
                ('amount_multiplier', models.DecimalField(decimal_places=1, default=3.0, max_digits=4)),
                ('night_start', models.IntegerField(default=1)),
                ('night_end', models.IntegerField(default=4)),
                ('trusted_recipients', models.JSONField(default=list)),
                ('email_alerts', models.BooleanField(default=True)),
                ('app_alerts', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fraud_detection_settings',
            },
        ),
    ]
